export * from './ClientAuthenticateMessage';
export * from './ClientLoadCharacterMessage';
export * from './ClientLoadCharactersListMessage';
export * from './ClientLoadChatsListMessage';
export * from './ClientResumeChatMessage';
export * from './ClientSendMessage';
export * from './ClientUpdateMessage';
export * from './ClientSpeechPlaybackCompleteMessage';
export * from './ClientSpeechPlaybackStartMessage';
export * from './ClientStopChatMessage';
export * from './ClientDeleteChatMessage';
export * from './ClientUpdateContextMessage';
export * from './ClientInspectAudioInputMessage';
export * from './ClientRevertMessage';
export * from './ClientRetryMessage';
export * from './ClientTriggerActionMessage';
export * from './ClientCaptureImageMessage';
export * from './ClientSubscribeToChatMessage';
export * from './ClientUnsubscribeFromChatMessage';
export * from './ClientAddChatParticipantMessage';
export * from './ClientRemoveChatParticipantMessage';
export * from './ClientPauseMessage';
export * from './ClientInterruptMessage';
export * from './ClientRunScriptMessage';
export * from './ClientCharacterSpeechRequestMessage';
export * from './ClientSpeakMessage';
export * from './ClientTypingEndMessage';
export * from './ClientTypingStartMessage';
export * from './ClientTriggerScriptEventMessage';
export * from './ClientInspectMessage';
export * from './ClientRequestSuggestionsMessage';
import { ClientAuthenticateMessage } from './ClientAuthenticateMessage';
import { ClientLoadCharacterMessage } from './ClientLoadCharacterMessage';
import { ClientLoadCharactersListMessage } from './ClientLoadCharactersListMessage';
import { ClientLoadChatsListMessage } from './ClientLoadChatsListMessage';
import { ClientResumeChatMessage } from './ClientResumeChatMessage';
import { ClientSendMessage } from './ClientSendMessage';
import { ClientUpdateMessage } from './ClientUpdateMessage';
import { ClientSpeechPlaybackCompleteMessage } from './ClientSpeechPlaybackCompleteMessage';
import { ClientSpeechPlaybackStartMessage } from './ClientSpeechPlaybackStartMessage';
import { ClientStopChatMessage } from './ClientStopChatMessage';
import { ClientDeleteChatMessage } from './ClientDeleteChatMessage';
import { ClientUpdateContextMessage } from './ClientUpdateContextMessage';
import { ClientInspectAudioInputMessage } from './ClientInspectAudioInputMessage';
import { ClientRevertMessage } from './ClientRevertMessage';
import { ClientRetryMessage } from './ClientRetryMessage';
import { ClientTriggerActionMessage } from './ClientTriggerActionMessage';
import { ClientCaptureImageMessage } from './ClientCaptureImageMessage';
import { ClientSubscribeToChatMessage } from './ClientSubscribeToChatMessage';
import { ClientUnsubscribeFromChatMessage } from './ClientUnsubscribeFromChatMessage';
import { ClientCharacterSpeechRequestMessage } from './ClientCharacterSpeechRequestMessage';
import { ClientAddChatParticipantMessage } from './ClientAddChatParticipantMessage';
import { ClientRemoveChatParticipantMessage } from './ClientRemoveChatParticipantMessage';
import { ClientPauseMessage } from './ClientPauseMessage';
import { ClientInterruptMessage } from './ClientInterruptMessage';
import { ClientRunScriptMessage } from './ClientRunScriptMessage';
import { ClientSpeakMessage } from './ClientSpeakMessage';
import { ClientTypingEndMessage } from './ClientTypingEndMessage';
import { ClientTypingStartMessage } from './ClientTypingStartMessage';
import { ClientTriggerScriptEventMessage } from './ClientTriggerScriptEventMessage';
import { ClientInspectMessage } from './ClientInspectMessage';
import { ClientRequestSuggestionsMessage } from './ClientRequestSuggestionsMessage';
export type ClientMessage = ClientAuthenticateMessage | ClientLoadCharactersListMessage | ClientLoadChatsListMessage | ClientLoadCharacterMessage | ClientResumeChatMessage | ClientSpeechPlaybackStartMessage | ClientSpeechPlaybackCompleteMessage | ClientSendMessage | ClientUpdateMessage | ClientStopChatMessage | ClientDeleteChatMessage | ClientSubscribeToChatMessage | ClientUnsubscribeFromChatMessage | ClientUpdateContextMessage | ClientInspectAudioInputMessage | ClientRevertMessage | ClientRetryMessage | ClientTriggerActionMessage | ClientCaptureImageMessage | ClientCharacterSpeechRequestMessage | ClientAddChatParticipantMessage | ClientRemoveChatParticipantMessage | ClientPauseMessage | ClientInterruptMessage | ClientRunScriptMessage | ClientSpeakMessage | ClientTypingEndMessage | ClientTypingStartMessage | ClientTriggerScriptEventMessage | ClientInspectMessage | ClientRequestSuggestionsMessage;
