import { ServiceDefinitionsApiClient } from './client/ServiceDefinitionsApiClient';
import { ModulesApiClient } from './client/ModulesApiClient';
import { PresetsApiClient } from './client/PresetsApiClient';
import { ChatsApiClient } from './client/ChatsApiClient';
import { CharactersApiClient } from './client/CharactersApiClient';
import { ServiceTypesApiClient } from './client/ServiceTypesApiClient';
import { MemoryBooksClient } from './client/MemoryBooksApiClient';
import { ScenariosApiClient } from './client/ScenariosApiClient';
import { VoicesApiClient } from './client/VoicesApiClient';
import { CulturesApiClient } from './client/CulturesApiClient';
import { DiagnosticsApiClient } from './client/DiagnosticsApiClient';
import { TextGenApiClient } from './client/TextGenApiClient';
import { VisionApiClient } from './client/VisionApiClient';
import { BenchmarksApiClient } from './client/BenchmarksApiClient';
import { ProfilesApiClient } from './client/ProfilesApiClient';
import { ImportApiClient } from './client/ImportApiClient';
import { AppsApiClient } from './client/AppsApiClient';
import { AugmentationsApiClient } from './client/AugmentationsApiClient';
import { PackagesApiClient } from './client/PackagesApiClient';
import { SummarizationApiClient } from './client/SummarizationApiClient';
import { AuthApiClient } from './client/AuthApiClient';
import { UsersApiClient } from './client/UsersApiClient';
import { ApiKeysApiClient } from './client/ApiKeysApiClient';
import { DeviceApiClient } from './client/DeviceApiClient';
import { UIApiClient } from './client/UIApiClient';
export declare class VoxtaApiClient {
    auth: AuthApiClient;
    serviceDefinitions: ServiceDefinitionsApiClient;
    modules: ModulesApiClient;
    presets: PresetsApiClient;
    chats: ChatsApiClient;
    characters: CharactersApiClient;
    serviceTypes: ServiceTypesApiClient;
    memoryBooks: MemoryBooksClient;
    scenarios: ScenariosApiClient;
    voices: VoicesApiClient;
    cultures: CulturesApiClient;
    diagnostics: DiagnosticsApiClient;
    textGen: TextGenApiClient;
    vision: VisionApiClient;
    benchmarks: BenchmarksApiClient;
    profiles: ProfilesApiClient;
    import: ImportApiClient;
    apps: AppsApiClient;
    augmentations: AugmentationsApiClient;
    packages: PackagesApiClient;
    summarization: SummarizationApiClient;
    users: UsersApiClient;
    apiKeys: ApiKeysApiClient;
    device: DeviceApiClient;
    ui: UIApiClient;
}
