export * from './ServerActionMessage';
export * from './ServerAuthenticationRequiredMessage';
export * from './ServerCharacterLoadedMessage';
export * from './ServerCharactersListLoadedMessage';
export * from './ServerChatsListLoadedMessage';
export * from './ServerConfigurationMessage';
export * from './ServerErrorMessage';
export * from './ServerChatStartingMessage';
export * from './ServerChatLoadingMessage';
export * from './ServerChatStartedMessage';
export * from './ServerUpdatedMessage';
export * from './ServerReplyChunkMessage';
export * from './ServerReplyEndMessage';
export * from './ServerReplyCancelledMessage';
export * from './ServerReplyStartMessage';
export * from './ServerSpeechRecognitionEndMessage';
export * from './ServerSpeechRecognitionPartialMessage';
export * from './ServerSpeechRecognitionStartMessage';
export * from './ServerWelcomeMessage';
export * from './ServerRecordingStatusMessage';
export * from './ServerSpeechPlaybackStartMessage';
export * from './ServerSpeechPlaybackCompleteMessage';
export * from './ServerContextUpdatedMessage';
export * from './ServerMemoryUpdatedMessage';
export * from './ServerChatSessionErrorMessage';
export * from './ServerReplyGeneratingMessage';
export * from './ServerChatClosedMessage';
export * from './ServerChatConfigurationMessage';
export * from './ServerAudioFrameMessage';
export * from './ServerRecordingRequestMessage';
export * from './ServerChatSessionsUpdatedMessage';
export * from './ServerChatParticipantsUpdatedMessage';
export * from './ServerChatFlowMessage';
export * from './ServerChatPausedMessage';
export * from './ServerActionAppTriggerMessage';
export * from './ServerMissingResourcesErrorMessage';
export * from './ServerInterruptSpeechMessage';
export * from './ServerVisionCaptureRequestMessage';
export * from './ServerWakeWordStatusMesssage';
export * from './ServerSuggestionsMessage';
import { ServerActionMessage } from './ServerActionMessage';
import { ServerAuthenticationRequiredMessage } from './ServerAuthenticationRequiredMessage';
import { ServerCharacterLoadedMessage } from './ServerCharacterLoadedMessage';
import { ServerCharactersListLoadedMessage } from './ServerCharactersListLoadedMessage';
import { ServerChatsListLoadedMessage } from './ServerChatsListLoadedMessage';
import { ServerConfigurationMessage } from './ServerConfigurationMessage';
import { ServerErrorMessage } from './ServerErrorMessage';
import { ServerChatStartingMessage } from './ServerChatStartingMessage';
import { ServerChatLoadingMessage } from './ServerChatLoadingMessage';
import { ServerChatStartedMessage } from './ServerChatStartedMessage';
import { ServerUpdatedMessage } from './ServerUpdatedMessage';
import { ServerReplyChunkMessage } from './ServerReplyChunkMessage';
import { ServerReplyEndMessage } from './ServerReplyEndMessage';
import { ServerReplyCancelledMessage } from './ServerReplyCancelledMessage';
import { ServerReplyStartMessage } from './ServerReplyStartMessage';
import { ServerSpeechRecognitionEndMessage } from './ServerSpeechRecognitionEndMessage';
import { ServerSpeechRecognitionPartialMessage } from './ServerSpeechRecognitionPartialMessage';
import { ServerSpeechRecognitionStartMessage } from './ServerSpeechRecognitionStartMessage';
import { ServerWelcomeMessage } from './ServerWelcomeMessage';
import { ServerRecordingStatusMessage } from './ServerRecordingStatusMessage';
import { ServerSpeechPlaybackStartMessage } from './ServerSpeechPlaybackStartMessage';
import { ServerSpeechPlaybackCompleteMessage } from './ServerSpeechPlaybackCompleteMessage';
import { ServerContextUpdatedMessage } from './ServerContextUpdatedMessage';
import { ServerMemoryUpdatedMessage } from './ServerMemoryUpdatedMessage';
import { ServerChatSessionErrorMessage } from './ServerChatSessionErrorMessage';
import { ServerReplyGeneratingMessage } from './ServerReplyGeneratingMessage';
import { ServerChatClosedMessage } from './ServerChatClosedMessage';
import { ServerChatConfigurationMessage } from './ServerChatConfigurationMessage';
import { ServerAudioFrameMessage } from './ServerAudioFrameMessage';
import { ServerRecordingRequestMessage } from './ServerRecordingRequestMessage';
import { ServerChatSessionsUpdatedMessage } from './ServerChatSessionsUpdatedMessage';
import { ServerChatParticipantsUpdatedMessage } from './ServerChatParticipantsUpdatedMessage';
import { ServerChatFlowMessage } from './ServerChatFlowMessage';
import { ServerChatPausedMessage } from './ServerChatPausedMessage';
import { ServerActionAppTriggerMessage } from './ServerActionAppTriggerMessage';
import { ServerMissingResourcesErrorMessage } from './ServerMissingResourcesErrorMessage';
import { ServerInterruptSpeechMessage } from './ServerInterruptSpeechMessage';
import { ServerVisionCaptureRequestMessage } from './ServerVisionCaptureRequestMessage';
import { ServerWakeWordStatusMesssage } from './ServerWakeWordStatusMesssage';
import { ServerSuggestionsMessage } from './ServerSuggestionsMessage';
export type ServerMessages = ServerWelcomeMessage | ServerAuthenticationRequiredMessage | ServerCharactersListLoadedMessage | ServerChatsListLoadedMessage | ServerCharacterLoadedMessage | ServerUpdatedMessage | ServerChatStartingMessage | ServerChatLoadingMessage | ServerChatStartedMessage | ServerReplyStartMessage | ServerReplyChunkMessage | ServerReplyEndMessage | ServerReplyCancelledMessage | ServerSpeechRecognitionStartMessage | ServerSpeechRecognitionPartialMessage | ServerSpeechRecognitionEndMessage | ServerActionMessage | ServerErrorMessage | ServerConfigurationMessage | ServerRecordingStatusMessage | ServerAudioFrameMessage | ServerRecordingRequestMessage | ServerChatSessionsUpdatedMessage | ServerChatParticipantsUpdatedMessage | ServerChatFlowMessage | ServerChatPausedMessage | ServerActionAppTriggerMessage | ServerMissingResourcesErrorMessage | ServerInterruptSpeechMessage | ServerVisionCaptureRequestMessage | ServerWakeWordStatusMesssage | ServerSuggestionsMessage;
export type VoxtaServerMessageEventMap = {
    error: CustomEvent<ServerErrorMessage>;
    welcome: CustomEvent<ServerWelcomeMessage>;
    authenticationRequired: CustomEvent<ServerAuthenticationRequiredMessage>;
    charactersListLoaded: CustomEvent<ServerCharactersListLoadedMessage>;
    chatsListLoaded: CustomEvent<ServerChatsListLoadedMessage>;
    characterLoaded: CustomEvent<ServerCharacterLoadedMessage>;
    chatStarting: CustomEvent<ServerChatStartingMessage>;
    chatLoadingMessage: CustomEvent<ServerChatLoadingMessage>;
    chatStarted: CustomEvent<ServerChatStartedMessage>;
    chatConfiguration: CustomEvent<ServerChatConfigurationMessage>;
    chatClosed: CustomEvent<ServerChatClosedMessage>;
    update: CustomEvent<ServerUpdatedMessage>;
    replyGenerating: CustomEvent<ServerReplyGeneratingMessage>;
    replyStart: CustomEvent<ServerReplyStartMessage>;
    replyChunk: CustomEvent<ServerReplyChunkMessage>;
    replyEnd: CustomEvent<ServerReplyEndMessage>;
    replyCancelled: CustomEvent<ServerReplyCancelledMessage>;
    speechRecognitionStart: CustomEvent<ServerSpeechRecognitionStartMessage>;
    speechRecognitionPartial: CustomEvent<ServerSpeechRecognitionPartialMessage>;
    speechRecognitionEnd: CustomEvent<ServerSpeechRecognitionEndMessage>;
    action: CustomEvent<ServerActionMessage>;
    configuration: CustomEvent<ServerConfigurationMessage>;
    recordingStatus: CustomEvent<ServerRecordingStatusMessage>;
    speechPlaybackStart: CustomEvent<ServerSpeechPlaybackStartMessage>;
    speechPlaybackComplete: CustomEvent<ServerSpeechPlaybackCompleteMessage>;
    contextUpdated: CustomEvent<ServerContextUpdatedMessage>;
    memoryUpdated: CustomEvent<ServerMemoryUpdatedMessage>;
    chatSessionError: CustomEvent<ServerChatSessionErrorMessage>;
    audioFrame: CustomEvent<ServerAudioFrameMessage>;
    recordingRequest: CustomEvent<ServerRecordingRequestMessage>;
    chatsSessionsUpdated: CustomEvent<ServerChatSessionsUpdatedMessage>;
    chatParticipantsUpdated: CustomEvent<ServerChatParticipantsUpdatedMessage>;
    chatFlow: CustomEvent<ServerChatFlowMessage>;
    chatPaused: CustomEvent<ServerChatPausedMessage>;
    appTrigger: CustomEvent<ServerActionAppTriggerMessage>;
    missingResourcesError: CustomEvent<ServerMissingResourcesErrorMessage>;
    interruptSpeech: CustomEvent<ServerInterruptSpeechMessage>;
    visionCaptureRequest: CustomEvent<ServerVisionCaptureRequestMessage>;
    wakeWordStatus: CustomEvent<ServerWakeWordStatusMesssage>;
    suggestions: CustomEvent<ServerSuggestionsMessage>;
};
